export const CATEGORIES_GET_START = 'CATEGORIES_GET_START';
export const CATEGORIES_GET_ERROR = 'CATEGORIES_GET_ERROR';
export const CATEGORIES_GET_SUCCESS = 'CATEGORIES_GET_SUCCES';

export const CATEGORIES_GET_ALL_START = 'CATEGORIES_GET_ALL_START';
export const CATEGORIES_GET_ALL_ERROR = 'CATEGORIES_GET_ALL_ERROR';
export const CATEGORIES_GET_ALL_SUCCESS = 'CATEGORIES_GET_ALL_SUCCESS';

export const CATEGORIES_SUB_GET_START = 'CATEGORIES_SUB_GET_START';
export const CATEGORIES_SUB_GET_ERROR = 'CATEGORIES_SUB_GET_ERROR';
export const CATEGORIES_SUB_GET_SUCCESS = 'CATEGORIES_SUB_GET_SUCCES';

export const CATEGORY_SAVE_START = 'CATEGORY_SAVE_START';
export const CATEGORY_SAVE_ERROR = 'CATEGORY_SAVE_ERROR';
export const CATEGORY_SAVE_SUCCESS = 'CATEGORY_SAVE_SUCCESS';

export const CATEGORY_UPDATE_START = 'CATEGORY_UPDATE_START';
export const CATEGORY_UPDATE_ERROR = 'CATEGORY_UPDATE_ERROR';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
